### ISSUE TITLE
Fitness dashboard not finding ANT devices

### ISSUE THREAD

**Issue by MedTechCD** [stuartlynne/fitness_hrv#1]
Hi, found this Github after posting the issue on the YouTube channel.
I have a Garmin USB stick correctly installed with the libusb-win32 version 1.2.6.0 (corrected with Zadig exe) but my Polar H10 is not found. It has the ANT enabled and it works fine with ergvideo connected by ANT.
ANT log file states
2022-06-28 12:13:57,354    ERROR | Open ERROR
2022-06-28 12:13:57,354 CRITICAL | Open CRITICAL

Fitness ECG is working correctly over BLE.

**Comment by MedTechCD** [comment]
Works with Alpha 0.17 v4

**Comment by MedTechCD** [comment]
Works with Alpha 0.17 v4

**Comment by stuartlynne** [comment]
Thanks for trying this, should have the alpha 0.17 available generally soon.
